name: Build Android APK (Docker)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure Git Safe Directory
      run: |
        git config --global --add safe.directory '*'

    - name: Build with Buildozer
      env:
        BUILDOZER_WARN_ON_ROOT: 0
      run: |
        yes | buildozer -v android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ronyxaudio-apk
        path: bin/*.apk
