name: Build Android APK (Docker)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure Git Safe Directory
      run: |
        git config --global --add safe.directory '*'

    - name: Inject Android SDK Licenses
      run: |
        mkdir -p ~/.android/licenses
        mkdir -p /github/home/.buildozer/android/platform/android-sdk/licenses
        
        HASHES=$'24333f8a637b82e1e5c3169f824214741a33a50a\n89330d3222db157f9a15d58d3111266e7a869504\nd56f518747945141a054625d12335f5842614343\n33b6a2b64607f11b759f320ef9dff4ae5c47d97a\n84831b9409646a918e30573bab4c9c91346d8abd'
        
        echo "$HASHES" > ~/.android/licenses/android-sdk-license
        echo "$HASHES" > /github/home/.buildozer/android/platform/android-sdk/licenses/android-sdk-license

    - name: Build with Buildozer
      env:
        BUILDOZER_WARN_ON_ROOT: 0
      run: |
        buildozer -v android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ronyxaudio-apk
        path: bin/*.apk
